### PR TITLE
Fix the esort and emark bug

### LINKED ISSUE #222: Fix bug between emark and esort
- [ ] fix bug when calling esort then emark
- [ ] fix bug when calling esort, emark and elist

### LINKED ISSUE #234: Mark and unmark with duplicate index bug
When the user attempts to enter the command `emark 2 2 1`, the app will not mark the events correctly. We should not allow duplicate indexes.

### PR DESCRIPTION
**Pull request by chunweii**
Closes #222 
Closes #234

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -283,7 +284,8 @@ public String toString() {
     @Override
     public boolean equals(Object other) {
         return other == this // short circuit if same object
-                || (other instanceof AddressBook // instanceof handles nulls
+            || (
+            other instanceof AddressBook // instanceof handles nulls
```
Comment (xiangjunn) [inline src/main/java/seedu/address/model/AddressBook.java:288]:
```suggestion
            || (other instanceof AddressBook // instanceof handles nulls
```

File: src/main/java/seedu/address/model/contact/Contact.java [hunk 2]
```diff
@@ -254,16 +260,40 @@ public Contact clearAllLinks() {
...
-                .append(getPhone() != null ? "; Phone: " + getPhone() : "") // optional
-                .append(getAddress() != null ? "; Address: " + getAddress() : "") // optional
-                .append(getZoomLink() != null ? "; Zoom Link: " + getZoomLink() : "") // optional
-                .append(getTelegramHandle() != null ? "; Telegram: " + getTelegramHandle() : ""); // optional
+            .append("; Email: ")
+            .append(getEmail())
+            .append(getPhone() != null ? "; Phone: " + getPhone() : "") // optional
+            .append(getAddress() != null ? "; Address: " + getAddress() : "") // optional
+            .append(getZoomLink() != null ? "; Zoom Link: " + getZoomLink() : "") // optional
+            .append(getTelegramHandle() != null ? "; Telegram: " + getTelegramHandle() : ""); // optional
```
Comment (xiangjunn) [inline src/main/java/seedu/address/model/contact/Contact.java:296]: Why are you changing all the indentations from 8 to 4 spaces? Java coding standard is 8 spaces for wrapped lines.

File: src/main/java/seedu/address/model/event/UniqueEventList.java [hunk 3]
```diff
@@ -180,7 +172,8 @@ public void updateEventMap() {
     @Override
     public boolean equals(Object other) {
         return other == this // short circuit if same object
-                || (other instanceof UniqueEventList // instanceof handles nulls
+            || (
+            other instanceof UniqueEventList // instanceof handles nulls
```
Comment (xiangjunn) [inline src/main/java/seedu/address/model/event/UniqueEventList.java:176]: Why did you split it like this?

**Review by xiangjunn — CHANGES_REQUESTED** [review]
LGTM!

**Review by xiangjunn — APPROVED** [review]
